### ISSUE TITLE
When checking which textbox has input both the handlers return false even when there is a value.

### ISSUE THREAD

**Issue by rdansro** [moneywent/money-went#8]
Console logs report false for a value despite a value being present in the textbox.

**Comment by Coopss** [comment]
Add duplication steps please.

**Comment by rdansro** [comment]
=STEPS=
-Load moneywent.com
-view the console 
-enter a value into a textbox
-click the "Let's find out button"
-The console reads false for both lines 258 and 259 in main.js,

=Outcome=
Console shows false.

=Expected Outcome=
If one of the textboxes has text it should read true? I could be misunderstanding this and it is functioning correctly.

**Comment by Coopss** [comment]
This was broken in https://github.com/moneywent/money-went/commit/0a08e9b4e003178e2f09be23dff36734ec3284a9

I will fix the check.
